export const items=[
    {
        id:1,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login'
    },
    {
        id:2,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/'
    },
    {
        id:3,
        title:'Cody',
        description:'Cody is an intelligent AI employee like ChatGPT - with the added benefit of being able to train it on your business, your team, your processes, and your clients. Use Cody to support your team or function as a highly-skilled employee that can analyze information, brainstorm ideas, and execute work.',
        url:'https://meetcody.ai/'
    },
    {
        id:4,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login'
    },
    {
        id:5,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/'
    },
    {
        id:6,
        title:'Cody',
        description:'Cody is an intelligent AI employee like ChatGPT - with the added benefit of being able to train it on your business, your team, your processes, and your clients. Use Cody to support your team or function as a highly-skilled employee that can analyze information, brainstorm ideas, and execute work.',
        url:'https://meetcody.ai/'
    },
    {
        id:7,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login'
    },
    {
        id:8,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/'
    },
    {
        id:9,
        title:'Cody',
        description:'Cody is an intelligent AI employee like ChatGPT - with the added benefit of being able to train it on your business, your team, your processes, and your clients. Use Cody to support your team or function as a highly-skilled employee that can analyze information, brainstorm ideas, and execute work.',
        url:'https://meetcody.ai/'
    },
    {
        id:10,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login'
    },
    {
        id:11,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/'
    },
    {
        id:12,
        title:'Cody',
        description:'Cody is an intelligent AI employee like ChatGPT - with the added benefit of being able to train it on your business, your team, your processes, and your clients. Use Cody to support your team or function as a highly-skilled employee that can analyze information, brainstorm ideas, and execute work.',
        url:'https://meetcody.ai/'
    }, {
        id:13,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login'
    },
    {
        id:14,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/'
    },
    {
        id:15,
        title:'Cody',
        description:'Cody is an intelligent AI employee like ChatGPT - with the added benefit of being able to train it on your business, your team, your processes, and your clients. Use Cody to support your team or function as a highly-skilled employee that can analyze information, brainstorm ideas, and execute work.',
        url:'https://chat.openai.com/auth/login'
    }
]