export const mostViewed=[
    {
        id:1,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login',
        rank:"001",
    },
    {
        id:2,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/',
        rank:"002",
    },
    {
        id:3,
        title:'Cody',
        description:'Cody is an intelligent AI employee like ChatGPT - with the added benefit of being able to train it on your business, your team, your processes, and your clients. Use Cody to support your team or function as a highly-skilled employee that can analyze information, brainstorm ideas, and execute work.',
        url:'https://meetcody.ai/',
        rank:"003",
    },
    {
        id:4,
        title:'ChatGPT',
        description:'ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.',
        url:'https://chat.openai.com/auth/login',
        rank:"004",
    },
    {
        id:5,
        title:'Adcreative.ai',
        description:'Adcreative.ai is an AI platform that generates hundreds of stunning, high-performing ad creatives in seconds!. Creatives generated by the Ai have a score which is the probability of that creative doing in your ad campaign.',
        url:'https://www.adcreative.ai/',
        rank:"005",
    },
]